- name: 'Execute a script on all web server nodes'
  hosts: web_nodes
  tasks:
  # LineInFile module
  - lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver 10.1.250.10'
  # Script module
  - name: 'Execute a script on all web server nodes'
    script: /tmp/install_script.sh
  # Service module
  - name: 'Start httpd services'
    service:
      name: httpd
      state: started
  # Command module
  - name: Display resolv.conf contents
    command: cat /etc/resolv.conf
  # User module
  - name: 'Create web_user and add to the developers group'
    user:
      name: web_user
      uid: 1040
      group: developers